<?php
/**
 * Incremental synchronization feed over the shared `sync_changes` log.
 *
 * Devices keep a local copy of the data they need so the app works
 * offline. This service answers the one question that keeps that copy
 * honest: "what changed since revision X?". Rows are appended to
 * `sync_changes` by database triggers (migration 057), so a change is
 * recorded no matter which endpoint or script performed it.
 *
 * Design notes:
 *   - The cursor is the `sync_changes.revision` AUTO_INCREMENT value.
 *     It is generated by the server and never derived from a device
 *     clock, so clock skew cannot reorder or hide a change.
 *   - Deletions travel as tombstones ({op: DELETE}) and carry no
 *     payload. Nothing is ever discovered by re-downloading a table.
 *   - A cursor older than the retention floor cannot be served a
 *     complete delta, so the caller is told to bootstrap rather than
 *     handed a quietly incomplete one.
 *   - The feed is permission scoped with the same primitives the normal
 *     endpoints use (apiIsClassRestricted / teacher_assignments), so a
 *     cursor can never surface rows the caller could not fetch directly.
 *
 * Migration 009's idempotency service is unaffected: reads are safe to
 * repeat, and replaying the same delta converges on the same local state.
 */
namespace App\Services;

final class SyncChangeFeedService
{
    /** Hard ceiling on rows per page, to bound responses on weak links. */
    public const MAX_LIMIT = 500;
    public const DEFAULT_LIMIT = 200;

    /** Entities this feed can serve. Extended one domain per phase. */
    public const SUPPORTED_ENTITIES = ['attendance'];

    /** How long a revision stays resumable before pruning. */
    public const RETENTION_DAYS = 30;

    private \mysqli $database;

    public function __construct(\mysqli $database)
    {
        $this->database = $database;
    }

    /**
     * True when the feed tables exist. Lets the endpoint degrade to a
     * clear "bootstrap required" answer while 057 is being rolled out,
     * instead of a 500 — and without creating schema in a request.
     */
    public function isAvailable(): bool
    {
        $result = $this->database->query(
            "SELECT 1 FROM information_schema.TABLES
              WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sync_changes' LIMIT 1"
        );
        return $result !== false && $result->num_rows > 0;
    }

    /**
     * Oldest revision still fully represented in the feed. A client
     * resuming from anything below this has missed changes that were
     * pruned, so it must bootstrap.
     */
    public function minValidRevision(): int
    {
        $result = $this->database->query(
            "SELECT min_valid_revision FROM sync_feed_state WHERE id = 1 LIMIT 1"
        );
        if ($result === false || $result->num_rows === 0) {
            return 0;
        }
        return (int)$result->fetch_assoc()['min_valid_revision'];
    }

    /** Highest revision currently assigned; the cursor a bootstrap starts from. */
    public function headRevision(): int
    {
        $result = $this->database->query("SELECT COALESCE(MAX(revision), 0) AS head FROM sync_changes");
        if ($result === false) {
            return 0;
        }
        return (int)$result->fetch_assoc()['head'];
    }

    /**
     * Does this cursor still allow a complete delta?
     *
     * Cursor 0 means "I have nothing yet" and always requires a
     * bootstrap. A positive cursor below the retention floor has lost
     * history and also requires one.
     */
    public function cursorIsResumable(int $cursor): bool
    {
        if ($cursor <= 0) {
            return false;
        }
        if ($cursor > $this->headRevision()) {
            // Ahead of the server: a restored backup or a wiped feed.
            // Resuming would silently skip everything in between.
            return false;
        }
        return $cursor >= $this->minValidRevision();
    }

    /**
     * Class ids the caller may receive changes for, or null when the
     * caller is not class restricted (admins, department roles).
     *
     * @return array<int,int>|null
     */
    public function visibleClassIds(int $userId, bool $classRestricted, int $yearId): ?array
    {
        if (!$classRestricted) {
            return null;
        }
        $statement = $this->database->prepare(
            "SELECT DISTINCT class_id FROM teacher_assignments
              WHERE teacher_id = ? AND is_active = 1
                AND class_id IS NOT NULL
                AND (academic_year_id IS NULL OR academic_year_id = ?)"
        );
        if (!$statement) {
            return [];
        }
        $statement->bind_param('ii', $userId, $yearId);
        $statement->execute();
        $result = $statement->get_result();
        $classIds = [];
        while ($row = $result->fetch_assoc()) {
            $classIds[] = (int)$row['class_id'];
        }
        $statement->close();
        return $classIds;
    }

    /**
     * One page of changes after $cursor.
     *
     * Returns the same envelope shape the hymn delta already uses
     * (items / next_cursor / server_time / has_more) so mobile code and
     * future domains share one contract.
     *
     * @param array<int,int>|null $visibleClassIds null = unrestricted
     * @return array{items:array<int,array<string,mixed>>,next_cursor:int,server_time:string,has_more:bool}
     */
    public function changesSince(
        int $cursor,
        string $entityType,
        ?array $visibleClassIds,
        int $limit = self::DEFAULT_LIMIT
    ): array {
        $limit = max(1, min($limit, self::MAX_LIMIT));

        // A class-restricted caller with no assignments sees an empty
        // feed, never the whole table.
        if ($visibleClassIds !== null && $visibleClassIds === []) {
            return [
                'items' => [],
                'next_cursor' => $cursor,
                'server_time' => gmdate('Y-m-d H:i:s'),
                'has_more' => false,
            ];
        }

        $sql = "SELECT revision, entity_type, entity_id, op, scope_class_id,
                       scope_year_id, scope_member_id, changed_at
                  FROM sync_changes
                 WHERE revision > ? AND entity_type = ?";
        $types = 'is';
        $params = [$cursor, $entityType];

        if ($visibleClassIds !== null) {
            $placeholders = implode(',', array_fill(0, count($visibleClassIds), '?'));
            $sql .= " AND scope_class_id IN ({$placeholders})";
            foreach ($visibleClassIds as $classId) {
                $types .= 'i';
                $params[] = (int)$classId;
            }
        }

        // One extra row tells us whether another page exists without a
        // second COUNT query.
        $sql .= " ORDER BY revision ASC LIMIT " . ((int)$limit + 1);

        $statement = $this->database->prepare($sql);
        if (!$statement) {
            return [
                'items' => [],
                'next_cursor' => $cursor,
                'server_time' => gmdate('Y-m-d H:i:s'),
                'has_more' => false,
            ];
        }
        $statement->bind_param($types, ...$params);
        $statement->execute();
        $result = $statement->get_result();

        $rows = [];
        while ($row = $result->fetch_assoc()) {
            $rows[] = $row;
        }
        $statement->close();

        $hasMore = count($rows) > $limit;
        if ($hasMore) {
            array_pop($rows);
        }

        $items = [];
        $nextCursor = $cursor;
        foreach ($rows as $row) {
            $nextCursor = (int)$row['revision'];
            $items[] = [
                'revision'    => (int)$row['revision'],
                'entity_type' => (string)$row['entity_type'],
                'entity_id'   => (int)$row['entity_id'],
                'op'          => (string)$row['op'],
                'changed_at'  => (string)$row['changed_at'],
            ];
        }

        return [
            'items' => $items,
            'next_cursor' => $nextCursor,
            'server_time' => gmdate('Y-m-d H:i:s'),
            'has_more' => $hasMore,
        ];
    }

    /**
     * Canonical payloads for the non-deleted ids in a page.
     *
     * The feed says what changed; this says what the row now is, so a
     * device can apply a delta without a second round trip per record.
     * Tombstoned ids are intentionally absent — a missing id in this map
     * is the signal to delete locally.
     *
     * @param array<int,int> $entityIds
     * @return array<int,array<string,mixed>> keyed by entity id
     */
    public function hydrateAttendance(array $entityIds): array
    {
        $entityIds = array_values(array_unique(array_map('intval', $entityIds)));
        if ($entityIds === []) {
            return [];
        }
        $placeholders = implode(',', array_fill(0, count($entityIds), '?'));
        $statement = $this->database->prepare(
            "SELECT id, member_id, class_id, academic_year_id, attendance_date,
                    status, check_in_time, check_out_time, notes, recorded_by, recorded_at
               FROM attendance
              WHERE id IN ({$placeholders})"
        );
        if (!$statement) {
            return [];
        }
        $statement->bind_param(str_repeat('i', count($entityIds)), ...$entityIds);
        $statement->execute();
        $result = $statement->get_result();

        $byId = [];
        while ($row = $result->fetch_assoc()) {
            $byId[(int)$row['id']] = [
                'id'               => (int)$row['id'],
                'member_id'        => (int)$row['member_id'],
                'class_id'         => $row['class_id'] === null ? null : (int)$row['class_id'],
                'academic_year_id' => $row['academic_year_id'] === null ? null : (int)$row['academic_year_id'],
                'attendance_date'  => (string)$row['attendance_date'],
                'status'           => (string)$row['status'],
                'check_in_time'    => $row['check_in_time'],
                'check_out_time'   => $row['check_out_time'],
                'notes'            => $row['notes'],
                'recorded_by'      => $row['recorded_by'] === null ? null : (int)$row['recorded_by'],
                'recorded_at'      => (string)$row['recorded_at'],
            ];
        }
        $statement->close();
        return $byId;
    }

    /**
     * Drop change records past the retention window and raise the
     * retention floor to match.
     *
     * The floor is raised to the highest pruned revision, so any cursor
     * at or below it is correctly treated as unresumable. Business rows
     * are never touched — only the synchronization history of them.
     *
     * @return array{pruned:int,min_valid_revision:int}
     */
    public function prune(int $retentionDays = self::RETENTION_DAYS): array
    {
        $retentionDays = max(1, $retentionDays);

        $statement = $this->database->prepare(
            "SELECT COALESCE(MAX(revision), 0) AS high FROM sync_changes
              WHERE changed_at < (NOW() - INTERVAL ? DAY)"
        );
        if (!$statement) {
            return ['pruned' => 0, 'min_valid_revision' => $this->minValidRevision()];
        }
        $statement->bind_param('i', $retentionDays);
        $statement->execute();
        $highestExpired = (int)$statement->get_result()->fetch_assoc()['high'];
        $statement->close();

        if ($highestExpired <= 0) {
            return ['pruned' => 0, 'min_valid_revision' => $this->minValidRevision()];
        }

        $delete = $this->database->prepare("DELETE FROM sync_changes WHERE revision <= ?");
        if (!$delete) {
            return ['pruned' => 0, 'min_valid_revision' => $this->minValidRevision()];
        }
        $delete->bind_param('i', $highestExpired);
        $delete->execute();
        $pruned = $delete->affected_rows;
        $delete->close();

        // Everything up to and including $highestExpired is gone, so the
        // oldest revision that can still be resumed from is the next one.
        $floor = $highestExpired + 1;
        $update = $this->database->prepare(
            "UPDATE sync_feed_state
                SET min_valid_revision = GREATEST(min_valid_revision, ?), pruned_at = NOW()
              WHERE id = 1"
        );
        if ($update) {
            $update->bind_param('i', $floor);
            $update->execute();
            $update->close();
        }

        return ['pruned' => (int)$pruned, 'min_valid_revision' => $this->minValidRevision()];
    }
}
